# taps
# tap "caarlos0/tap"
# tap "caskroom/cask"
# tap "caskroom/fonts"
# tap "caskroom/versions"
# tap "eqnxio/ngrok"
# tap "getantibody/tap"
# tap "go-delve/delve"
# tap "goreleaser/tap"
# tap "heroku/brew"
# tap "homebrew/bundle"
# tap "homebrew/core"
# tap "homebrew/services"
# tap "neovim/neovim"
# tap "qvl/tap"
# tap "valelint/vale"
# tap "wata727/tflint"

# tools
brew "adr-tools"
brew "asciinema"
brew "awscli"
brew "caarlos0/tap/clone-org"
brew "caarlos0/tap/fork-cleaner"
brew "cloc"
brew "coreutils"
brew "curl"
brew "dep"
brew "diff-so-fancy"
brew "eqnxio/ngrok/ngrok"
brew "exa"
brew "fd"
brew "ffmpeg"
brew "findutils"
brew "fzf"
brew "gawk"
brew "gdb"
brew "getantibody/tap/antibody"
brew "gifsicle"
brew "gnu-getopt"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnupg"
brew "gnutls"
brew "go-delve/delve/delve", args: ["HEAD"]
brew "go"
brew "gpg-agent"
brew "graphviz"
brew "heroku/brew/heroku"
brew "hub"
brew "hugo"
brew "imagemagick"
brew "ipcalc"
brew "jemalloc"
brew "jq"
brew "kops"
brew "kubernetes-helm"
brew "libyaml"
brew "maven"
brew "mercurial"
brew "msgpack"
brew "ncdu"
brew "neovim"
brew "nmap"
brew "pinentry-mac"
brew "pstree"
brew "rbenv"
brew "redis"
brew "ripgrep"
brew "rpm"
brew "shellcheck"
brew "snapcraft"
brew "stern"
brew "telnet"
brew "terraform"
brew "tldr"
brew "travis"
brew "tree"
brew "unrar"
brew "valelint/vale/vale"
brew "vim"
brew "watch"
brew "wget"
brew "wrk"
brew "yarn"
brew "zsh"

# casks
cask "appcleaner"
cask "authy-desktop"
cask "betterzipql"
cask "caffeine"
cask "caskroom/fonts/font-firacode-nerd-font-mono"
cask "caskroom/fonts/font-firacode-nerd-font"
cask "caskroom/versions/iterm2-beta"
cask "disk-inventory-x"
cask "docker"
cask "google-chrome"
cask "intellij-idea-ce"
cask "java"
cask "keybase"
cask "kindle"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "skype"
cask "slack"
cask "slate"
cask "spotify"
cask "suspicious-package"
cask "telegram"
cask "visual-studio-code"
cask "vlc"
cask "webpquicklook"
cask "whatsapp"
